# 넘파이(umpy)

In [ ]:
# 필요한 라이브러리 임포트
import numpy as np

## 넘파이 배열과 파이썬 리스트 비교

In [ ]:
# 파이썬 리스트 자료 구조 데이터 생성
list_data = [1,2,3]
print(f'파이썬 리스트: {list_data}')

print('-'*80)

# 넘파이 배열 생성
array_data = np.array(list_data)
print(f'넘파이 배열로 변한 후 데이터: {array_data}')

파이썬 리스트: [1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열로 변한 후 데이터: [1 2 3]

In [ ]:
# 파이썬 리스트와 넘파이 배열 차이점 확인

## 덧셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한 덧셈 연산의 결과: \n{result1}')

print('-'*80)

### 넘파이 배열
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')

print('-'*80)

## 곱셈 연산

### 파이썬 리스트
result3 = []

for num in list_data:
    result3.append(num*3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: \n{result3}')

print('-'*80)

### 넘파이 배열
result4 = array_data * 3
print(f'넘파이 배열에 대한 곱셈 연산의 결과: \n{result4}')

print('-'*80)

## 통계 처리(평균 값 구하기)

### 파이썬 리스트
list_average = sum(list_data) / len(list_data)
print(f'파이썬 리스트에 대한 평균 값: {list_average}')

print('-'*80)

### 넘파이 배열
array_average = array_data.mean()
print(f'넘파이 배열에 대한 평균 값: {array_average}')

파이썬 리스트에 대한 덧셈 연산의 결과:
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과:
[2 4 6]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 곱셈 연산의 결과:
[3, 6, 9]
--------------------------------------------------------------------------------
넘파이 배열에 대한 곱셈 연산의 결과:
[3 6 9]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 평균 값: 2.0
--------------------------------------------------------------------------------
넘파이 배열에 대한 평균 값: 2.0

In [ ]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성(조건: 성분 원소의 개수 동일)
list_data = [[1,2,3],[4,5,6],[7,8,9]]
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 엑셀과 같은 표(table: 행과 열) 구조 생성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료 구조 데이터 확인:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

## 2차원 배열 생성

In [ ]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성(조건: 성분 원소의 개수 동일)
list_data = [[1,2,3],[4,5,6]]
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 2차원 배열 -> 엑셀과 같은 표(table: 행과 열) 구조 생성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료 구조 데이터 확인:
[[1, 2, 3], [4, 5, 6]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과:
[[1 2 3]
 [4 5 6]]

## 인덱싱

In [ ]:
# 목표: 첫 번째 행, 첫 번째 열 -> 1 추출

## 파이썬 방식

### 1단계: 변수[인덱스] -> 첫 번째 행 추출
result1 = array_data[0]
print(result1)

print('-'*80)

### 2단계: 변수[인덱스] -> 첫 번째 성분(첫 번째 열) 원소
# result2 = result1[0]
result2 = array_data[0][0]
print(result2)

print('-'*80)

## 넘파이 방식: 넘파이의 배열 모양(2행,3열) 이용 -> 변수[행 인덱스, 열 인덱스]
result3 = array_data[0,0]
print(f'숫자 1을 인덱싱한 결과: {result3}')

[1 2 3]
--------------------------------------------------------------------------------
1
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과: 1

# 넘파이 연습 문제

In [ ]:
# 문제1
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print(f'결과: {arr1 + arr2}')

결과: [11 22 33]

In [ ]:
# 문제2
data = [5, 10, 15]
arr_data = np.array(data)
multi = arr_data*3
print(f'배열 곱셈 결과: {multi}')

배열 곱셈 결과: [15 30 45]

In [ ]:
# 문제3
arr = np.array([10, 30, 50, 70, 90])
average = arr.mean()
print(f'평균값: {average}')

평균값: 50.0

In [ ]:
# 문제4
list_2d = [[10, 20], [30, 40]]
arr_2d = np.array(list_2d)
print(f'2차원 배열:\n{arr_2d}')

2차원 배열:
[[10 20]
 [30 40]]

In [ ]:
# 문제5
result = arr_2d[1, 1]
print(f'추출된 숫자: {result}')

추출된 숫자: 40

# 판다스(pandas)

In [ ]:
# 필요한 라이브러리 임포트
import pandas as pd

## DataFrame 자료 구조 생성: csv 파일 처리

In [ ]:
# colab과 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

In [44]:
# DataFrame 생성

## 파일 경로(위치) 설정
file_path = "/content/drive/MyDrive/KDT/ad_performance.csv"

## pd.read_csv() 호출
df = pd.read_csv(file_path)

## 결과 확인
# print(df)
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

## 분해

In [47]:
# 행 인덱스 추출
info_index = df.index
print(f'DataFrame의 행 인덱스: {info_index}')

print('-'*80)

# 컬럼 인덱스 추출
info_columns = df.columns
print(f'DataFrame의 컬럼 인덱스: {info_columns}')

print('-'*80)

# 값 추출
info_values = df.values
print(f'DataFrame의 값: \n{info_values}')

DataFrame의 행 인덱스: RangeIndex(start=0, stop=5000, step=1)
--------------------------------------------------------------------------------
DataFrame의 컬럼 인덱스: Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')
--------------------------------------------------------------------------------
DataFrame의 값:
[['2025-01-01' 'Facebook' '50s+' ... 100308 27 723225]
 ['2025-01-01' 'Google' '20s' ... 103029 26 1680444]
 ['2025-01-01' 'Naver' '50s+' ... 158046 48 1580303]
 ...
 ['2025-06-29' 'Organic' '40s' ... 159162 20 795243]
 ['2025-06-29' 'Google' '20s' ... 173437 23 1293372]
 ['2025-06-29' 'Naver' '30s' ... 193294 13 1000870]]

## 인덱싱

In [49]:
# 특정 컬럼 인덱싱 -> 결과: Series 자료 구조 생성
channel = df["Channel"]
print(channel)

0       Facebook
1         Google
2          Naver
3        Organic
4          Naver
          ...
4995     Organic
4996       Naver
4997     Organic
4998      Google
4999       Naver
Name: Channel, Length: 5000, dtype: object

In [51]:
# fancy 인덱싱: 변수[['컬럼1','컬럼4','컬럼3',...]]
df1 = df[['Channel','Clicks','Revenue']]
# print(df1)
display(df1)

       Channel  Clicks  Revenue
0     Facebook     578   723225
1       Google     897  1680444
2        Naver     471  1580303
3      Organic     686   520546
4        Naver     525  1505721
...        ...     ...      ...
4995   Organic     933   814096
4996     Naver     537   256452
4997   Organic     378   795243
4998    Google     124  1293372
4999     Naver     733  1000870

[5000 rows x 3 columns]

In [55]:
print(df['Clicks']/df['Impressions'] * 100)

0        3.750324
1        7.481234
2        2.545533
3        9.991261
4       10.000000
          ...
4995     9.270668
4996     9.492664
4997     5.156186
4998     1.337360
4999     5.777112
Length: 5000, dtype: float64